### PR TITLE
BSD support

### PR DESCRIPTION
**Pull request by sedmicha**
Modifications to make ipfixcol2 buildable on BSD systems (tested on FreeBSD 15)

Building with Clang is recommended, as GCC seems to cause some issues

### CODE REVIEW

**Comment by sedmicha** [comment]
@mzary

**Comment by mzary** [comment]
So far the daemon runs fine, log files are stored and readable, and the plugins which I was able to test seem to work fine.
I have updated https://github.com/mzary/ipfixcol2/tree/main but it's probably not ready for submission to FreeBSD ports tree yet. We can do it when the bsd-support branch is merged with the master and a new release will be prepared. 

The port of libfds is ready for submission, but it will be nice to incorporate this patch[1] in future releases of this library if it won't break Linux builds.

1. https://github.com/mzary/ipfixcol2/blob/main/net-mgmt/libfds/files/patch-include_libfds_converters.h

**Comment by sedmicha** [comment]
> So far the daemon runs fine, log files are stored and readable, and the plugins which I was able to test seem to work fine. I have updated https://github.com/mzary/ipfixcol2/tree/main but it's probably not ready for submission to FreeBSD ports tree yet. We can do it when the bsd-support branch is merged with the master and a new release will be prepared.
> 
> The port of libfds is ready for submission, but it will be nice to incorporate this patch[1] in future releases of this library if it won't break Linux builds.
> 
> 1. https://github.com/mzary/ipfixcol2/blob/main/net-mgmt/libfds/files/patch-include_libfds_converters.h

Thank you for your testing efforts, I appreciate it. We have been a bit too busy with other projects lately, but I am still keeping an eye on this.

**Comment by mzary** [comment]
I just wanted to let you know, that after half a year, after a few rebuilds and updates of the underlying OS and software, the daemon still runs fine and does the job as intended. I still hope that BSD-related patches will get merged into the main branch and that a new release will be created, but if you don't plan to merge BSD patches soon, perhaps it's the right time to create a port for FreeBSD and base it on bsd-support branch, since the software is reliable and does the job fine.

**Comment by Lukas955** [comment]
Thanks for the feedback, the fixes are now part of the main branch.

**Comment by mzary** [comment]
Thank you for merging the branches. I will prepare the port for the FreeBSD ports tree and submit it next week, but it will be easier to base it on the tag instead of hooking it on the commit hash. Do you plan a new release soon?

**Comment by sedmicha** [comment]
> Thank you for merging the branches. I will prepare the port for the FreeBSD ports tree and submit it next week, but it will be easier to base it on the tag instead of hooking it on the commit hash. Do you plan a new release soon?

Thank you for your support. We have just released ipfixcol2 v2.6.0 and libfds v0.6.0 which include the necessary changes for BSD support.

**Comment by mzary** [comment]
Thank you very much for your effort in making ipfixcol2 work under FreeBSD. By the end of the week, I will submit the PRs (problem reports) to add libfds and ipfixcol2 to the FreeBSD ports tree. I hope they will get accepted and committed soon. I will keep you updated.

**Comment by mzary** [comment]
Two new ports have just officially entered the FreeBSD ports tree[1][2]. Now it's time to get ready for more bug reports ;-)
Thanks again to @sedmicha,  @Lukas955 and all the CESNET staff for their efforts to modify the code to be BSD-friendly, without which this would never have been possible. Many thanks also to eugen@freebsd.org for the quick commiting of these ports.

1. https://github.com/freebsd/freebsd-ports/commit/cddafadedf0c08eea8af0af13b91c2e815d8f522
2. https://github.com/freebsd/freebsd-ports/commit/ce7dc5c30bde171cb3aa9c17d19c0a330e9a9909

**Pull request merged**
